const productos = [
  {
    id:1,
    titulo: "Ciudades 1",
    categoria: "Ciudades",
    precio: 100,
    img: "urlIMG",
    colorMarco: ["Natural", "Negro", "Blanco"],
    descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id:2,
    titulo: "Botanicos 1",
    categoria: "Botanicos",
    precio: 600,
    img: "urlIMG",
    colorMarco: ["Natural", "Negro", "Blanco"],
    descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id:3,
    titulo: "Infantiles 1",
    categoria: "Infantiles",
    precio: 450,
    img: "urlIMG",
    colorMarco: ["Negro", "Blanco"],
    descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id:4,
    titulo: "Abstractos 1",
    categoria: "Abstractos",
    precio: 2000,
    img: "urlIMG",
    colorMarco: ["Negro", "Blanco"],
    descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id:6,
    titulo: "Abstractos 2",
    categoria: "Abstractos",
    precio: 1500,
    img: "urlIMG",
    colorMarco: ["Negro", "Blanco"],
    descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id:7,
    titulo: "Abstractos 3",
    categoria: "Abstractos",
    precio: 500,
    img: "urlIMG",
    colorMarco: ["Natural", "Negro"],
    descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id:8,
    titulo: "Botanicos 2",
    categoria: "Botanicos",
    precio: 200,
    img: "urlIMG",
    colorMarco: ["Natural", "Negro"],
    descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id:9,
    titulo: "Ciudades 2",
    categoria: "Ciudades",
    precio: 960,
    img: "urlIMG",
    colorMarco: ["Natural", "Blanco"],
    descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id:10,
    titulo: "Ciudades 3",
    categoria: "Ciudades",
    precio: 290,
    img: "urlIMG",
    colorMarco: ["Natural", "Negro"],
    descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
  {
    id:11,
    titulo: "Abstractos 4",
    categoria: "Abstractos",
    precio: 1900,
    img: "urlIMG",
    colorMarco: ["Natural", "Blanco"],
    descripcion: "Lorem ipsum dolor sit amet, consectetur adipiscing elit",
  },
];


